//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP4Sim.CSharpAgents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewCSStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewCSStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GP4Sim.CSharpAgents.NewCSStrings", typeof(NewCSStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string ClassFooter {
            get {
                return ResourceManager.GetString("ClassFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///public class AgentClass
        ///{
        ///.
        /// </summary>
        internal static string ClassHeader {
            get {
                return ResourceManager.GetString("ClassHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if(double.IsNegativeInfinity(f[0]) || double.IsPositiveInfinity(f[0]))
        ///          f[0] = 0;
        ///       
        ///       return f[0];
        ///    }.
        /// </summary>
        internal static string FunctionFooter {
            get {
                return ResourceManager.GetString("FunctionFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public double GPFunction(Dictionary&lt;string,Func&lt;double&gt;&gt; InputVars, Dictionary&lt;string,Func&lt;double&gt;&gt; InternalStates)
        ///{
        ///       double[] f = new double[8];
        ///       f[0]=f[1]=f[2]=f[3]=f[4]=f[5]=f[6]=f[7]=0.0;
        ///       bool[] flagstack = new bool[8];
        ///       int fc = 0;
        ///.
        /// </summary>
        internal static string FunctionHeader {
            get {
                return ResourceManager.GetString("FunctionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to };
        ///.
        /// </summary>
        internal static string VarsFooter {
            get {
                return ResourceManager.GetString("VarsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public List&lt;string&gt; Vars = new List&lt;string&gt;
        ///{.
        /// </summary>
        internal static string VarsHeader {
            get {
                return ResourceManager.GetString("VarsHeader", resourceCulture);
            }
        }
    }
}
